[package]
name = "vg-gateway"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
async_from.workspace = true
dashmap.workspace = true
enumflags2.workspace = true
futures.workspace = true
getset.workspace = true
http.workspace = true
opentelemetry.workspace = true
pingora.workspace = true
thiserror.workspace = true
tokio.workspace = true
typed-builder.workspace = true
vg-core = { path = "../core" }
vg-config = { path = "../config" }
vg-http = { path = "../http" }
vg-rpc-client = { path = "../rpc-client" }