[package]
name = "vg-rpc"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
derive_more.workspace = true
getset.workspace = true
http.workspace = true
http-serde-ext.workspace = true
jsonrpsee = { workspace = true, features = ["macros", "tracing", "client-core", "server-core"] }
num-traits.workspace = true
num-derive.workspace = true
opentelemetry.workspace = true
opentelemetry-http.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
typed-builder.workspace = true
vg-config = { path = "../config" }