[package]
name = "vg-rpc"
version = "0.0.0"
edition = "2024"

[features]
default = []
client = ["jsonrpsee/client"]
server = ["jsonrpsee/server"]

[dependencies]
async-trait.workspace = true
jsonrpsee = { workspace = true, features = ["tracing", "macros"] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
vg-config = { path = "../config" }