[package]
name = "vg-kube"
version = "0.0.0"
edition = "2024"

[lib]
name = "vg_kube"
path = "src/lib.rs"

[features]
default = ["config"]
config = [
    "base64ct",
    "vg-http-config"
]

[dependencies]
assertables.workspace = true
base64ct = { workspace = true, optional = true }
derive_more.workspace = true
gateway-api.workspace = true
getset.workspace = true
http.workspace = true
ipnet.workspace = true
k8s-openapi.workspace = true
kube = { workspace = true, features = ["kube-derive", "derive"] }
kube-core.workspace = true
kube-leader-election.workspace = true
multi-map.workspace = true
ouroboros.workspace = true
paste.workspace = true
regex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
typed-builder.workspace = true
vg-core = { path = "../core" }
vg-http-config = { path = "../http-config", optional = true }

[build-dependencies]
serde_yaml.workspace = true