[package]
name = "vg-http"
version = "0.0.0"
edition = "2024"

[dependencies]
assertables.workspace = true
async-trait.workspace = true
derive_more.workspace = true
bytes.workspace = true
getset.workspace = true
heck.workspace = true
hickory-proto.workspace = true
http.workspace = true
ipnet.workspace = true
opentelemetry.workspace = true
pingora.workspace = true
problemdetails.workspace = true
regex.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
tower = { workspace = true, features = ["util"] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
trusted-proxies.workspace = true
typed-builder.workspace = true
tokio.workspace = true
url.workspace = true
vg-core = { path = "../core" }
vg-config = { path = "../config" }

[dev-dependencies]
criterion.workspace = true
futures.workspace = true
mockall.workspace = true
rstest.workspace = true
serde_json.workspace = true
tower-test.workspace = true