[package]
name = "vg-core"
version = "0.0.0"
edition = "2024"

[lib]
name = "vg_core"
path = "src/lib.rs"

[dependencies]
assertables.workspace = true
schemars.workspace = true
serde.workspace = true
tokio.workspace = true
tokio.features = ["full", "tracing"]
tokio-shutdown.workspace = true
tracing.workspace = true