pub mod cluster;
pub mod common;
pub mod kind;
mod macros;
pub mod namespace;

use crate::api::v1::http::filter::access_control::AccessControlFilter;
use crate::api::v1::http::filter::client_addr::ClientAddressFilter;
use crate::api::v1::http::filter::error_response::ErrorResponseFilter;
use crate::api::v1::http::filter::static_response::StaticResponseFilter;
use crate::api::v1::parameters::{GatewayClassParameters, GatewayParameters};
use crate::{cluster_scope, namespace_scope};
pub use cluster::*;
pub use common::*;
use gateway_api::gatewayclasses::GatewayClass;
use gateway_api::gateways::Gateway;
use gateway_api::httproutes::HTTPRoute;
use k8s_openapi::api::apps::v1::Deployment;
use k8s_openapi::api::core::v1::{ConfigMap, Service};
use k8s_openapi::api::discovery::v1::EndpointSlice;
pub use kind::*;
pub use namespace::*;

cluster_scope!(GatewayClass);
cluster_scope!(GatewayClassParameters);
namespace_scope!(Service);
namespace_scope!(EndpointSlice);
namespace_scope!(ConfigMap);
namespace_scope!(Deployment);
namespace_scope!(GatewayParameters);
namespace_scope!(Gateway);
namespace_scope!(HTTPRoute);
namespace_scope!(AccessControlFilter);
namespace_scope!(ErrorResponseFilter);
namespace_scope!(ClientAddressFilter);
namespace_scope!(StaticResponseFilter);
