[package]
name = "vg-rpc-server"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
dashmap.workspace = true
getset.workspace = true
http.workspace = true
derive_more.workspace = true
jsonrpsee = { workspace = true, features = ["tracing", "server"] }
jsonrpsee-core.workspace = true
opentelemetry.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-layer.workspace = true
tracing.workspace = true
typed-builder.workspace = true
vg-core = { path = "../core" }
vg-config = { path = "../config" }
vg-rpc = { path = "../rpc" }