[package]
name = "vg-rpc-client"
version = "0.0.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
async_from.workspace = true
derive_more.workspace = true
getset.workspace = true
http.workspace = true
jsonrpsee = { workspace = true, features = ["tracing", "ws-client"] }
thiserror.workspace = true
tokio.workspace = true
typed-builder.workspace = true
vg-config = { path = "../config" }
vg-rpc = { path = "../rpc" }