[package]
name = "vg-controller"
version = "0.0.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
http.workspace = true
derive_more.workspace = true
thiserror.workspace = true
tokio.workspace = true
typed-builder.workspace = true
vg-core = { path = "../core" }
vg-config = { path = "../config" }
vg-rpc-server = { path = "../rpc-server" }