[package]
name = "vg-api"
version = "0.1.0"
edition = "2021"

[dependencies]
gateway-api = { workspace = true }
ipnet = { workspace = true }
k8s-openapi = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
typed-builder = { workspace = true }

[lib]
name = "vg_api"
path = "src/lib.rs"
